replicaCount: 1

image:
  repository: dataopennesscommunity/demo-golden
  pullPolicy: Always
  tag: "latest"

service:
  type: ClusterIP
  port: 5201
  targetPort: 5201

ingress:
  enabled: true
  pathPrefix: /genai-response
  proxy-connect-timeout: 300
  proxy-send-timeout: 300
  proxy-read-timeout: 300
  
resources: {}
